### ISSUE TITLE
Which caffe version supports ceil_mode in Pooling?

### ISSUE THREAD

**Issue by quietsmile** [shicai/DenseNet-Caffe#1]
Nice work!
However, I found that ceil_mode is not supported in the master version of caffe.
Is there an open-sourced caffe version that supports ceil_mode in pooing? Thanks.

**Comment by shicai** [comment]
@quietsmile pls see: https://github.com/BVLC/caffe/pull/3057/files
just add several lines of code.

**Comment by quietsmile** [comment]
Oh, this is interesting. I mean, is it compatible with cudnn_pooling implementation? Or, just to make the output a little bit larger,  even though the elements in the last row/col may still be zeros? 

Thanks.

**Comment by shicai** [comment]
As i know, cudnn does not support ceil mode, but you'd better check cudnn manual by yourself.
I use caffe's own pooling layer to support ceil mode.

**Comment by oujieww** [comment]
can anyone sent me your caffe? I don't know which version of caffe should be used. I have tried to use a order version without working.But the new caffe didn't have vision_layers.hpp . I don't know what to do.please help me.

**Comment by Sarah635** [comment]
New version doesnot have vision_layers.hpp. In new version the file pooling_layer.hpp is to be modified.

**Comment by JinmingZhao** [comment]
@Sarah635 I have the same problem ,how to modify on the new version?

**Comment by Sarah635** [comment]
https://github.com/BVLC/caffe/pull/3057/files

Follow this link. Add the + lines and delete the - lines. 

Instead of file vision_layers.hpp,, modify the file pooling_layers.hpp. Modify these 3 files i.e. pooling_layers.hpp, pooling_layers.cpp and caffe.proto according to link above and you are done.

**Comment by JinmingZhao** [comment]
@Sarah635  Thank you very much, done!

**Comment by ShockeenLee** [comment]
都修改了，但是生成报错：错误	1	error C2039: “ceil_mode”: 不是“caffe::PoolingParameter”的成员	E:\caffe-master\caffe-master\src\caffe\layers\pooling_layer.cpp	38	1	libcaffe

**Comment by XUYUNYUN666** [comment]
> @Sarah635 Thank you very much, done!

Need I change the code of pooling layer.cu? Thank U.

**Comment by keerthanss** [comment]
With the latest version of Caffe, you can also get around this by replacing "ceil_mode: false" with "round_mode: FLOOR". No editing of Caffe source code necessary. Refer https://github.com/BVLC/caffe/pull/6282 .

**Comment by lijiansong** [comment]
@keerthanss 
When I run DenseNet-201, I get the following error, it seems that caffe fail to parse the `DenseNet_201.caffemodel`

```
layer[1002].clip_param.max
F1118 11:10:19.095713 30557 upgrade_proto.cpp:97] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: DenseNet_201.caffemodel
*** Check failure stack trace: ***
    @     0x7f3e5d2af5cd  google::LogMessage::Fail()
    @     0x7f3e5d2b1433  google::LogMessage::SendToLog()
    @     0x7f3e5d2af15b  google::LogMessage::Flush()
    @     0x7f3e5d2b1e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3e5da70731  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f3e5da9b4fa  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @           0x4091ff  test()
    @           0x407310  main
    @     0x7f3e5c21f830  __libc_start_main
    @           0x407b39  _start
    @              (nil)  (unknown)
```

**Comment by mrgransky** [comment]
@keerthanss  I tried both `ceil_mode: false` and `round_mode: FLOOR` for `deploy.prototxt` file in DenseNet161 in `caffe-gpu` installed via conda, I get the error explained here: #37 .
