### ISSUE TITLE
what's your batch size?

### ISSUE THREAD

**Issue by WormCoder** [shicai/DenseNet-Caffe#13]
Hi, I am training Densenet-121. When the batch size is larger than about 25, out of memory occurs. I'm using a work station with 8 TITANＸPascal GPUs, so I can't achieve batch size larger than 200... 
What's your batch size when you trained these nets?

**Comment by shicai** [comment]
256.
you can use batch size of 128 (16x8),  and lower the initial base_lr to 0.05 from 0.1.

**Comment by WormCoder** [comment]
thanks, do you use random resize of the image's shorter side for data argumentation?

**Comment by shicai** [comment]
I use scale and aspect ratio augmentation.

**Comment by WormCoder** [comment]
thanks, so you must modify the data_transformer of caffe
 what's your scale range?

**Comment by WormCoder** [comment]
thanks, so you must modify the data_transformer of caffe
what's your scale range?

**Comment by shicai** [comment]
please refer to: https://github.com/facebook/fb.resnet.torch/blob/master/datasets/transforms.lua#L130

**Comment by WormCoder** [comment]
thanks
