### ISSUE TITLE
The shapes in netscope are wrong?

### ISSUE THREAD

**Issue by bluemandora** [shicai/DenseNet-Caffe#20]
In pool1, the input spatial shape is 112 and ceil_mode = false.
So the output shape will be `floor((112-3+2)/2+1) = 56`
Does this equal to "padding = 'SAME'" in tensorflow? Which `output_spatial_shape[i] = ceil(input_spatial_shape[i] / strides[i])`

**Comment by shicai** [comment]
The output shape of this pooling layer is the same as 3x3 convolution with stride=2 in 'same' mode.
So you may be right.

**Comment by courosh** [comment]
@shicai 
The ceil_mode flag doesn't seem to be working in netscope. For example, I have a layer that is 64 x 64. If I do a convolution with kernel_size = 3, pad = 1, stride = 2, the output size is 32 x 32. However, if I do a pooling layer with kernel_size = 3, pad = 1, stride = 2, the output size is 33 x 33, regardless of whether ceil_mode: true or ceil_mode: false. According to BVLC/caffe #3057 (https://github.com/BVLC/caffe/pull/3057/files) it's a simple matter to add this capability. Can this be done? Thanks.
