### ISSUE TITLE
DenseNet和Faster R-CNN的结合

### ISSUE THREAD

**Issue by foralliance** [shicai/DenseNet-Caffe#23]
想将该DenseNet121模型作为Faster R-CNN的基础网络去实现，基于您给的DenseNet_121.prototxt文件做了如下修改来生成train.prototxt
　　1. 数据输入按照Faster R-CNN的去写
　　2. 对于conv layers ，添加1次{ lr_mult: 1 decay_mult: 1}
　　3. 对于batchnorm layers，添加3次 {lr_mult: 0 decay_mult: 0} 
　　4. 对于scale layers，添加2次param {lr_mult: 1　decay_mult: 0｝
　　5. RPN，ROI Proposal， RCNN，这3部分基本照搬Faster R-CNN中VGG16的去写．做了如下修改：
　　　1.  RPN部分的bottom改为：conv4_blk
　　　2.  R-CNN部分的bottom改为：conv5_blk/bn"
　　　3.  R-CNN部分原来的fc6层改名为fc6_1
　　您给的prototxt文件中的＂最后的fc6层＂和＂倒数第2个Pooling层＂我直接删除了
　　其他的基本没变．现有如何疑问：
　　1. 不知道上述那样的修改是否妥当？？
　　2. 对于Faster R-CNN中的test.prototxt，输入，RPN，ROI Proposal， RCNN这4部分还是按照Faster R-CNN中VGG16的去写．但对于中间的网络部分怎么修改？？也要像2,3,4步那样去修改增加对应的param吗？？
 　　3. solver文件怎么写，有没有一些参考？？我这里基本是照搬Faster R-CNN中VGG16的．

**Comment by foralliance** [comment]
为了验证文件是否配置正确，我就只训练了10000次．
最终的效果很差，基本检测不到物体．不知道哪里的参数设置的不对．comp4_xxx.txt中全为空

**Comment by leepp15** [comment]
请问下对于每个需要修改的层，有什么简便方法可以批量快速修改吗？比如“对于所有conv layers ，添加1次{ lr_mult: 1 decay_mult: 1}”。苦恼两天了～

**Comment by Yangjayhui** [comment]
请问，DenseNet和Faster R-CNN的结合，最后的效果怎么样

**Comment by Yangjayhui** [comment]
请问，DenseNet和Faster R-CNN的结合，最终效果怎么样？

**Comment by CrzayJay** [comment]
请问DenseNet和Faster R-CNN的结合，最后效果怎么样，收敛了吗
