### ISSUE TITLE
Not achieving your reported performance! 

### ISSUE THREAD

**Issue by HelloTobe** [shicai/DenseNet-Caffe#25]
Hi, thanks for your work!
I follow your instruction and run DenseNet121 but only get   **0.715681**  top-1 accuracy and  **0.904023**  top-5 accuracy.
I guess it may be caused by the dataset.  I use val_lmdb(ressize to 256x256) and crop to 224x224 in the train.prototxt for testing. But for you, it's  here:
**The top-1/5 accuracy rates by using single center crop (crop size: 224x224, image size: 256xN)**.
Do you use the original val images for testing? I  really  don't know what to do to produce 256xN image size.
I find your another reply about image_size here: [http://www.caffecn.cn/?/question/428](url)
I get more confused about 10 crops. Can you take a minute to explain it to me?

**Comment by shicai** [comment]
使用原始尺寸的图像做Validation，原始图像不管长宽多少，都可以按比例将其最短边缩放到256，长边是N，然后在这个图像上裁剪最中间的224x224。10 Crops就是在图像里面裁剪10个不同的区域，送入神经网络，然后得到概率然后平均，这样性能会更好。

**Comment by HelloTobe** [comment]
@shicai Thanks a lot!
1）每次测试都使用原始图像作为，会比用val_lmdb慢很多，而且没法在训练的同时验证；
或是这样：训练前把256xN裁剪得到的224x224图片变成lmdb，这样10个crop得到10个lmdb。
你是怎么做的?  144 crop时以上方法应该都不行，有什么好办法吗？
2）10个输入得到概率取平均，我感觉不能通过python脚本实现，是不是要修改caffe源码？
3）googlenet和resnet等论文里的ensemble model是不是也是多个模型输入取概率平均？

PS：大神能微博私信你吗

**Comment by shicai** [comment]
做验证的时候，我只用single crop，multi crop的pycaffe代码github到处都是，你自己找下就好了。
ensemble一般都是多个模型，论文中肯定有写用了几个模型，你找找。
