### ISSUE TITLE
revise deploy.prototxt

### ISSUE THREAD

**Issue by xizi** [shicai/DenseNet-Caffe#9]
Hi, shicai, can i directly revise deploy.prototxt to get trainval.prototxt and what is the need to pay attention to detail?

**Comment by shicai** [comment]
yes.
- add data layers, and loss/accuracy layers
- add param {  lr_mult: 1 decay_mult: 1} for conv layers
- add param {  lr_mult: 0 decay_mult: 0} for 3 times for  each batchnorm layer
- add fillers for conv and scale layers if not finetuing

**Comment by gittigxuy** [comment]
caffe新手，可否将上面的回复转化为trainval.prototxt的内容写一下

**Comment by yuanyuanli85** [comment]
I think you can refer to code to generate deploy and train_val prototxt. 
https://github.com/liuzhuang13/DenseNetCaffe/
or https://github.com/yuanyuanli85/DenseNet-Caffe

**Comment by dlyldxwl** [comment]
请问一下，为什么bn层需要加3次呢，不是只有两个参数吗，而且这两个参数也是不用学习的呀

**Comment by shicai** [comment]
caffe默认的batchnorm层有3个参数，正是因为这些参数是需要计算而不是需要训练的，所以才需要将lr_mult和decay_mult设置为0。

**Comment by dlyldxwl** [comment]
谢谢回答！我看了一下源码，第三个参数大概是滑动系数和的意思，前两个分别是mean的和、var的和。但是我看了一下你的densenet model为啥第三个系数值是1呢，你做了reshape吗？

**Comment by dlyldxwl** [comment]
错了，我可视化的是你的nobilenet model的conv1/bn里的第三个参数值是1。你训练的model很赞，给力！

**Comment by shicai** [comment]
thx~
